---
abstract: 'yet another forking process controller'
author:
  - 'Alex White <VVu@geekfarm.org>'
build_requires:
  English: 0
  File::Temp: 0
  IO::File: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Launcher
requires:
  Carp: 0
  File::Path: 0
  File::Tail: 0
  Mouse: 0
  Mouse::Role: 0
  POSIX: 0
resources:
  repository: http://github.com/wu/Proc-Launcher
version: 0.0.35
